### ISSUE TITLE
Python 3.12 cannot use from other projects

### ISSUE THREAD

**Issue by scivision** [valgur/ncompress#2]
Georinex is a project using ncompress that fails with Python 3.12 on any OS: https://github.com/geospace-code/georinex/actions/runs/7683841372/job/20939652614

I also see this on a local computer with Python 3.12.1:

```python
>>> import ncompress
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniconda3\envs\py312\Lib\site-packages\ncompress\__init__.py", line 2, in <module>
    from .ncompress_core import compress, decompress
ModuleNotFoundError: No module named 'ncompress.ncompress_core'
```

**Comment by valgur** [comment]
Thanks for letting me know. I'll look into it right away.

**Comment by valgur** [comment]
@scivision The issues you saw were caused by the source distributions on PyPI missing CMakeLists.txt for some reason. I added an extra test against that to the pipeline and it has apparently resolved on its own, somehow.

I also added a new v1.0.2 release with Python 3.12 stable ABI wheels.

Thanks again for the bug report!
