### ISSUE TITLE
Is it possible to write output stream while decompressing?

### ISSUE THREAD

**Issue by eddyizm** [valgur/ncompress#4]

**Comment by valgur** [comment]
There is currently no way to interleave other operations with decompression. I have been thinking about refactoring the decompression logic into a class instead of a single-shot function to support chunked decompression, but I have not had any need for it so far, so working on this has not been a priority for me.

**Comment by eddyizm** [comment]
Ok, I was not seeing it so just wanted to make sure. Definitely a challenge for large files. Thanks for the response!
